import { Inter } from "next/font/google";
import { Varela_Round } from "next/font/google";
import Navbar from "./components/navbar";
import "./globals.css";
import { GlobalProvider } from "./context/GlobalContext.js";

const inter = Inter({ subsets: ["latin"] });
const varela_round = Varela_Round({ subsets: ["latin"], weight: "400" });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={varela_round.className}>
                <GlobalProvider>
                    <header>
                        <Navbar />
                    </header>
                    <main>{children}</main>
                </GlobalProvider>
            </body>
        </html>
    );
}
